// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWBsSR8K-gcZydGkXXPNrdbFvS23mowI',
    appId: '1:1046338056599:web:89780a2a91f00b94ac94d2',
    messagingSenderId: '1046338056599',
    projectId: 'aucs-df68c',
    authDomain: 'aucs-df68c.firebaseapp.com',
    storageBucket: 'aucs-df68c.firebasestorage.app',
    measurementId: 'G-FJTEG1HWE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYcrPJiQ2XE0TfoND0gvHdcGmQ94gMjA',
    appId: '1:1046338056599:android:cfe296b46e24aeb7ac94d2',
    messagingSenderId: '1046338056599',
    projectId: 'aucs-df68c',
    storageBucket: 'aucs-df68c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuHtkC1obUez04zuh_pLacVd6rw4T0Y8',
    appId: '1:1046338056599:ios:0b8620fc5ee0b951ac94d2',
    messagingSenderId: '1046338056599',
    projectId: 'aucs-df68c',
    storageBucket: 'aucs-df68c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuHtkC1obUez04zuh_pLacVd6rw4T0Y8',
    appId: '1:1046338056599:ios:0b8620fc5ee0b951ac94d2',
    messagingSenderId: '1046338056599',
    projectId: 'aucs-df68c',
    storageBucket: 'aucs-df68c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfWBsSR8K-gcZydGkXXPNrdbFvS23mowI',
    appId: '1:1046338056599:web:46f196c63dd1968eac94d2',
    messagingSenderId: '1046338056599',
    projectId: 'aucs-df68c',
    authDomain: 'aucs-df68c.firebaseapp.com',
    storageBucket: 'aucs-df68c.firebasestorage.app',
    measurementId: 'G-TPESX7D40N',
  );
}
